### PR TITLE
Initial extraction of method getCellXml from addRow

### PR DESCRIPTION
**Pull request by nimmneun**
makes addRow more readable + moving a little more towards single responsibility principle.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @nimmneun, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by nimmneun** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @nimmneun has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by adrilo** [comment]
👍

**Comment by adrilo** [comment]
Should we do the same thing for https://github.com/box/spout/blob/1d3a9f939c43bfa6f2827f21ebb1c6e625847dee/src/Spout/Writer/ODS/Internal/Worksheet.php#L135?

**Comment by nimmneun** [comment]
@adrilo you mean renaming the method getCellContent to getCellXml? I have to admit ... at first sight I thought getCellContent would just return the content (value) of a cell, not the xml =) But the method itself is already properly extracted. Renaming for consistency would be a good move though :+1:

**Comment by adrilo** [comment]
See #306

**Pull request merged**
