### PR TITLE
Add some documentation on read data from specific sheet

### PR DESCRIPTION
**Pull request by agasigp**
I just made some change on the documentation. I think I need to add it because I have problem when first time I use your library. I don't know how to access the value of cell, so I went to stackoverflow and then finally found the answer. With this PR, I hope nobody will face the same Issue/problem like me anymore.

### CODE REVIEW

**Comment by agasigp** [comment]
CLA signed

**Comment by boxcla** [comment]
I couldn't find a signed CLA for @agasigp. Can you please try again?

**Comment by agasigp** [comment]
"CLA signed"

**Comment by boxcla** [comment]
I couldn't find a signed CLA for @agasigp. Can you please try again?

**Comment by agasigp** [comment]
"CLA signed".

**Comment by boxcla** [comment]
I couldn't find a signed CLA for @agasigp. Can you please try again?

**Comment by agasigp** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @agasigp has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by adrilo** [comment]
@agasigp I expect people to start reading the "Getting started" and "Documentation" before reading the "Guides" section. This section lists some recipes to do common things with Spout but does indeed assume that the reader is familiar with how Spout works. I'd rather keep it this way for now.

**Pull request closed without merging**
