### PR TITLE
Option to keep empty rows

### LINKED ISSUE #230: Unable to recover original row index from XLSX reader
Hi there @adrilo et al,

in an XLSX file, completely empty rows seem to be omitted from the XML altogether. This means that for a sheet like the following example

    1 | Title  |      |
    2 |        |      |
    3 | Data   | Data |
    4 | Data   | Data |

the indices returned from `$reader->getSheetIterator()` will be assigned like this:

    0 | Title
    1 | Data
    2 | Data

which means that it's not possible to recover the original row positions (indices). This is an issue if you want to point to users to specific rows / cells in their sheets.

One possible solution would be to modify the `RowIterator` so that the index (key) returned matches the actual row number, i.e.:

    1 | Title
    3 | Data
    4 | Data

However, this clearly is a BC break, so before I make a PR, I would like to hear your opinion on this one... Thanks!

### PR DESCRIPTION
**Pull request by adrilo**
Fixes #230

This change adds a new setting to readers: preserving empty rows. Currently, Spout skips empty rows but for some users, it may be useful to keep them. This is now possible with all readers.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @adrilo has signed the CLA. Thanks for the pull request!

**Comment by adrilo** [comment]
FYI @KiNgMaR @madflow @Rushleader

**Comment by madflow** [comment]
I did a quick test and this will work for my use case for this feature. Thanks! 

Maybe worth noticing that the options setters have to be called before the reader is opened.

Also: The ods reader/writer created a different result with my test code:

https://gist.github.com/madflow/c2ccef2409fac04544cf9c7537bbcfb6

**Comment by adrilo** [comment]
Cool, thanks for taking a look @madflow !

**Pull request merged**
