### PR TITLE
Add full support for PHP 8.0

### PR DESCRIPTION
**Pull request by skodak**
Unfortunately due to PHPUnit 8.5 dependency this also drops support for PHP 7.1.

I did not know what version to use due to the bump in minimal PHP version, so I guessed it would be 3.2

### CODE REVIEW

**Comment by skodak** [comment]
This is not a real pull request, I just wanted to see how much work it would be. I understand that dropping support for PHP 7.1 and 7.2 might make some people a bit angry.

**Review by adrilo — APPROVED** [review]

**Comment by adrilo** [comment]
Thanks @skodak ! I think it's fair to deprecate PHP 7.1 (EOL was 1+ year ago: https://www.php.net/supported-versions.php)

**Comment by jmsche** [comment]
@adrilo Could you please tag 3.2.0 soon? Or do you need other PRs to be fixed/merged before?

**Comment by jmsche** [comment]
@adrilo friendly ping :)

**Comment by adrilo** [comment]
Done :)

**Comment by jmsche** [comment]
Thank you :)

**Pull request merged**
