### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by philipbrown**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @philipbrown, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by philipbrown** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @philipbrown has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by adrilo** [comment]
Thanks! :+1:

**Pull request merged**
