### PR TITLE
Hyperlink Support

### PR DESCRIPTION
**Pull request by 97WaterPolo**
Adaptation of a previous version PR https://github.com/box/spout/pull/352

I found the pull request for a previous version while seeing if native Hyperlink support was added. I personally don't need any other "formulas" just the HYPERLINK to have clickable cells to external websites. Not sure if this will be useful but it is just added the regex and xml from the above PR. First ever PR so not sure if I am doing this right, but a small change if anyone needs hyperlinks like me.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @97WaterPolo, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by 97WaterPolo** [comment]
> Hi @97WaterPolo, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla
> 
> Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

CLA Signed (if this is a valid PR)

**Comment by boxcla** [comment]
Verified that @97WaterPolo has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by adrilo** [comment]
Hi @97WaterPolo !
Thanks for submitting your first PR. We try to have the same features for XLSX and ODS files. So I can't accept this PR as is (+ broken/missing tests). Anyway, I'll leave it open so that people can use what you did in their project/fork.

**Comment by GuidoLeibbrand** [comment]
> Hi @97WaterPolo !
> Thanks for submitting your first PR. We try to have the same features for XLSX and ODS files. So I can't accept this PR as is (+ broken/missing tests). Anyway, I'll leave it open so that people can use what you did in their project/fork.

I think this feature also very good.
Can you describe @adrilo what still needs to be done so that this PR is accepted.
How must the hyperlink syntax look like that it fits?

Another possibility would be not only to set the cell values from outsite 
Means other (xlsx, ods) xml elements.

**Pull request closed without merging**
