### PR TITLE
Enhancement related to issue #172...  

### PR DESCRIPTION
**Pull request by sfichera**
Enhancement related to issue #172...

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @sfichera, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by sfichera** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @sfichera has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by adrilo** [comment]
It looks great! Do you mind adding a test for it?
You can add a CSV file with custom line endings in the `tests/resources/csv` folder and use this file in your test. It should be straightforward :)

**Comment by adrilo** [comment]
:+1:  Thanks!

**Pull request merged**
