### PR TITLE
column width - issue 118

### PR DESCRIPTION
**Pull request by silversailor**
Added possibility to set column width, as explained in issue 118
nothing fancy, but functionnal

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @silversailor, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by silversailor** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @silversailor has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by glukkkk** [comment]
@silversailor Why not using PSR-2?

**Comment by hotabjn** [comment]
@silversailor Can you help me with functional which you wrote? For setting columns width I used Xlsx\Writer::setColumnsWidth() and in created file was no changes. XDebug shows me that columnwidths array received in Worksheet::startSheet(). What can I do wrong?

**Comment by pntabuye** [comment]
So this was never merged to master ?
To bad. 
I'll patch my checkout then.

**Comment by adrilo** [comment]
[CLEANUP] This PR is more than 1 year old. Closing it.

**Pull request closed without merging**
