### PR TITLE
bump phpunit to the latest supported release, travis setup, ignore co…

### PR DESCRIPTION
**Pull request by madflow**
* bump phpunit to the latest supported release 5.7 that supports PHP 5.6 (EOL is 2018-02) 
* travis setup
* ignore composer.lock (should not be part of libraries)

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @madflow has signed the CLA. Thanks for the pull request!

**Comment by adrilo** [comment]
To fix Scrutinizer, you may need to update .scrutinizer.yml (the after_script section)

**Comment by madflow** [comment]
I pinned the coverage to only send data in PHP 7.1 and rebased. However - the Scrutinizer job took unusually long. This could be just a coincidence (worker queue full or sth...) I guess... I can monitor this in the next commits.

**Comment by adrilo** [comment]
Indeed, it took forever !! Right, we'll see if that's only a temporary issue.

**Pull request merged**
