### PR TITLE
Fix issue #218 - ODS Reader does not read text in hyperlinks

### PR DESCRIPTION
**Pull request by madflow**
Fix issue #218 - ODS Reader does not read text in hyperlinks

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @madflow has signed the CLA. Thanks for the pull request!

**Comment by adrilo** [comment]
👍 Can you please rebase? I can't merge the commit otherwise

**Comment by madflow** [comment]
- [x]  **rebased**

**Comment by adrilo** [comment]
Hmmm my bad, I just pushed new commits into master. You'll need to rebase one more time :(

**Comment by madflow** [comment]
- [x] re-rebased

**Pull request merged**
