### PR TITLE
Some bug fixes, and BIFF5 XLS export support, and HTML export support

### PR DESCRIPTION
**Pull request by chrisgraham**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @chrisgraham, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by chrisgraham** [comment]
I can't sign the CLA, as some code still remains from https://gist.github.com/ihumanable/929039
We're just talking a couple of class variables and incrementer functions for them, and some known hex values for writing out XLS header information. I'll see if I can get a clarification on CLA of that from the author.

**Comment by nzakas** [comment]
Hi @chrisgraham thanks so much for your contribution. While we'd like to incorporate some of these changes, we really need you to separate different fixes into separate pull requests. This pull request has a lot of changes for a lot of different issues, which makes it very hard to evaluate. 

We have some basic guidelines for pull requests in our contributor's guide that you might find useful:
https://github.com/box/spout/blob/master/CONTRIBUTING.md

In general, we're looking for one pull request per bug fix/enhancement, and ideally, an issue describing the bug/enhancement you're addressing. That way, we can evaluate each individually and we can merge in the ones that make sense while working through the ones we aren't quite sure of.

It looks like you have some good changes in there, and we'd like to incorporate some, we just really need them organized a bit better so we can properly evaluate them.

Thanks!

**Comment by chrisgraham** [comment]
@nzakas Unfortunately I don't have any more time to volunteer. I did all this stuff as an emergency, when my client's testing found PHP-Excel was running out of memory on tiny sheets, it was for a ~2-day project that went over-time into a ~4-day project. I'm afraid practically speaking, nobody's going to cover my costs carefully organising pull requests.

**Comment by nzakas** [comment]
Thanks @chrisgraham, we completely understand. Unfortunately, we're not able to accept this pull request in it's current form. It would also take a lot of our time to individually investigate each commit you made and understand the implications of merging them in, and that's very hard to do without understanding the problems you were trying to address.

To close the loop, would you be willing to write up a bulleted list of bugs you found so that we can file issues and investigate? We do appreciate the time you spent looking into problems, and would like that effort to lead to improvements for all of our consumers. At least with this list, we have a jumping-off point to continue your work.

**Comment by chrisgraham** [comment]
How about you add me on Skype, ocproducts-chrisg. I'll then talk it all over with you. Probably easiest way, as we can talk design decisions too.

**Comment by nzakas** [comment]
That sounds like a good idea. Probably best to talk with @adrilo directly.

**Comment by adrilo** [comment]
@chrisgraham, I'd be happy to Skype with you. Before doing so, can you please split this pull request into multiple, so that I can better understand all the changes you are trying to make. It will help for the discussion!

**Comment by chrisgraham** [comment]
It's not even possible. For example, the support for URL-support I added is implemented in my HTML writer. So we have cross-cutting things here. I'd need to drip them out over time, as prior ones are approved, adjusting based on your changes.
My client could barely afford the spreadsheet export work I just did for them (actually I made a 100% loss on it) and definitely isn't going to fund me to take a day or so carefully coordinating upstream fixes, so any time I spend here would have to be my personal time, and it's already taken up with a lot of commitments. Creating a fork was pragmatic, becoming a heavily-involved active contributor is a much bigger commitment and I just can't afford it (literally). I feel like an asshole saying that, but it's the truth, I don't have anyone sponsoring my ongoing Open Source time.
I'll close this pull request. If you want to cherry-pick stuff from my fork you're very welcome to. If I am able to get some funding from one of my clients to continue work on Excel systems, I'll try and come back and contribute again.

**Comment by nzakas** [comment]
@chrisgraham that's fine, we understand. @adrilo can you set up a time to Skype with @chrisgraham? I'm betting he can pretty quickly give you an overview of the problems he ran into, and then we can figure out how to go from there.

**Pull request closed without merging**
