### PR TITLE
Change Worksheet function visibility from private to protected

### PR DESCRIPTION
**Pull request by WebsourceCz**
We have created small package on top of the Spout for support cell number format and per cell styles, so we need to call parent functions.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @WebsourceCz, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by WebsourceCz** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @WebsourceCz has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by adrilo** [comment]
@WebsourceCz I can merge the changes but I can't guarantee that it won't change in the future.

**Pull request merged**
