### PR TITLE
Add support for writing date cells

### PR DESCRIPTION
**Pull request by guss77**
The ODS writer is missing support for cells of type `DateTime` to use the ODS cell type `office:date-value`. This code also puts in the `calcext` types... because it doesn't hurt, I guess?

### CODE REVIEW

**Comment by guss77** [comment]
huh. apparently I already submitted a PR about this a while back: #752 to fix issue #751.

I'm closing that PR because this one is superior and works with Microsoft ODS imports.

**Comment by aphofstede** [comment]
https://travis-ci.org/github/box/spout/builds/724420903

**Comment by guss77** [comment]
@aphofstede - I'm not really sure what broke there: it looks like `vendor/bin/php-cs-fixer fix` failed? I don't even know what that is. If you can, if appreciate if you can explain what is wrong. I'll also try to run the CI locally and see if I can repro, tomorrow.

**Comment by guss77** [comment]
Ok, it still fails, but all the rest are PHP docs which are not part of what I changed. I can fix them if you want. Let me know.

**Comment by marzoli** [comment]
Merge please

**Comment by Slamdunk** [comment]
Merged in https://github.com/openspout/openspout/pull/8

**Comment by guss77** [comment]
merged upstream

**Pull request closed without merging**
