### PR TITLE
Adding coveralls.io support

### PR DESCRIPTION
**Pull request by adrilo**
Updated TravisCI config, using:
- http://docs.travis-ci.com/user/languages/php/
- https://github.com/satooshi/php-coveralls#travis-ci

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @adrilo has signed the CLA. Thanks for the pull request!

**Comment by Lewiscowles1986** [comment]
Did not realize this was here, can you add the badge to the readme.md and remove the now unnecesarry phpunit xml coveralls (See #62 I did not realize you had a commit, I was in my own repo :+1: )

**Comment by adrilo** [comment]
I was just testing stuff ! Let's merge yours as you did all the work :)

**Comment by Lewiscowles1986** [comment]
No no, I don't care who gets merged, I just need this so I can ensure I don't forget to check coverage and write tests for the PHPUnit :+1:

**Pull request merged**
