### PR TITLE
General should not be interpreted as a date format for number cells

### PR DESCRIPTION
**Pull request by da-eto-ya**
Fix issue #212 (Numeric cells with automatic formatting being converted to date)

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @da-eto-ya, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by da-eto-ya** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @da-eto-ya has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by adrilo** [comment]
Hey @da-eto-ya, I just saw your pull request. Did not notice it before I pushed #221.
We took pretty much the same approach (I used the ID instead of the string "General"). Going to close this pull request, since I already merged the other one.

Thanks for your contribution!

**Pull request closed without merging**
