### PR TITLE
support branch alias

### PR DESCRIPTION
**Pull request by garak**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @garak, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by garak** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @garak has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by adrilo** [comment]
Can you give more context on why this is needed? Is it in order download the latest version, before it's released? Also, isn't the "dev-master" branch defined by default?

**Comment by garak** [comment]
I found myself in the need of getting last commits. Requiring ``dev-master`` is dangerous, since this project can go ahead with incompatible changes (e.g. with major releases).
With branch alias, I can safely require ``2.4.*@dev``

**Comment by adrilo** [comment]
Does the branch alias needs to be updated every time the version is bumped (from 2.3 to 2.4 or 3 for instance)? The current version is 2.3.x so should the dev-master always be one version ahead?

**Comment by garak** [comment]
Of course

**Comment by adrilo** [comment]
BTW @garak, I just created a release for 2.4. You should be able to pull the latest changes in your project now!

**Comment by garak** [comment]
Thank you @adrilo

**Comment by garak** [comment]
@adrilo I just noticed that branch alias now is still pointing to 2.4. As already discussed, It should point to 2.5.

**Comment by adrilo** [comment]
Fixing it here: #162

**Pull request merged**
