### PR TITLE
Fix writer usage example docs

### PR DESCRIPTION
**Pull request by troytft**
Hello, I found undefined variable `$writer` in docs example

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @troytft, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by troytft** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @troytft has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by adrilo** [comment]
Thanks @troytft !

**Pull request merged**
